### ISSUE TITLE
Parse expanded objects recursively into RecordModel

### ISSUE THREAD

**Issue by LuxF3rre** [pocketbase/dart-sdk#14]
Currently when calling `client.records.getFullList('collection', query: {'expand': 'relation1.relation2.relation3.'});` the result is a RecordModel but objects nested in expand are of type Map. Changing the nested objects into RecordModel (recursively) would make it easier to work with the expand option.

![image](https://user-images.githubusercontent.com/2528538/192136526-762c9ad5-2148-41e4-b0ed-56d7f3a32b47.png)

**Comment by ganigeorgiev** [comment]
Expand is of `Map<String, dynamic>` because you can have single and multiple relation records expansion, aka. it could be Map<String, Record|List<Record>>.

I'm not sure if we can change the `dynamic` part, but I'll consider for the next release to run at least each expanded record through the Record model factory so that we can normalize the fields and allow users to do direct type assertions if they know that the referencing expand field is a single record or list (eg. `record.expand["incestment"] as Record`).

**Comment by ganigeorgiev** [comment]
For easier and unified record(s) access, `RecordModel.expand` is now always `Map<String, List<RecordModel>>` (even for single relation fields). When calling `RecordModel.toJson()` the original expand format is preserved.

This change will be available with the upcoming `v0.5-dev` release that will be compatible with PocketBase v0.8. You could expect a release sometime at the end of the week (or the next one at the latest). All v0.5 SDK changes are listed under the temporary v0.8-dev compatible branch - https://github.com/pocketbase/dart-sdk/blob/v0.8-dev/CHANGELOG.md (it will be soon merged in master; the main PocketBase v0.8-dev branch is not published since there are still some unit tests that need to be fixed).
