### ISSUE TITLE
Migrating Database Collections from dart

### ISSUE THREAD

**Issue by iampopal** [pocketbase/dart-sdk#28]
We have been using the package: drift https://drift.simonbinder.eu/, 
drift has a great feature of Migrating Database from the Client Side, 
here is a guide to migration: 
https://drift.simonbinder.eu/docs/advanced-features/migrations/ 

We need to get the current version of the database and then do some migration by dart code: 
* Adding a Column to a collection
* Removing a Column from a collection
* Changing collection name 
* Renaming a Column

We need the above feature because of the following reasons:
1) Our app will be used offline first and then back up its database to the cloud. 
2) Our app will be installed on the user's device, so when we bring a new feature a column may add or remove automatically by opening their database. 

Waiting for a guide on how to do Migration from the dart side.

**Comment by ganigeorgiev** [comment]
There is no official offline/local-first data handling for now.

PocketBase [v0.9+](https://github.com/pocketbase/pocketbase/releases/tag/v0.9.0) supports writing external migrations with JS (_more documentation on that will be available soon_).
It also comes with automigrate functionality, aka. when doing collection changes in the UI or via the web APIs it will automatically generate a js/go migration file inside `pb_migrations` that you can commit to your repo. Migrations are executed automatically server start (aka. `./pocketbase serve`).

I'm not sure that I understand your use case, but you can use the [`pb.collections.*`](https://github.com/pocketbase/dart-sdk#collectionservice-detailed-class-reference-api-docs) apis (_you'll have to be authenticated as admin in order to be able to modify the collections_) since they will trigger the automigrate functionality.

**Comment by iampopal** [comment]
Can you show us an example of adding a new column to a collection or
removing a column from a collection

**Comment by iampopal** [comment]
About auto migration
Can you please show us an example of how updating or adding of a column
work there
And
How we can put migrating files in our repo and start a new project with the
same tables

**Comment by iampopal** [comment]
We want to have a database where users server will be at their own computer

When we ship a new version of our application adding columns or renaming
column shall be done automatically

Please tell us the best way we can do it ☝️

**Comment by ganigeorgiev** [comment]
> Can you show us an example of adding a new column to a collection or
removing a column from a collection

Here is an example using the Dart SDK (_I haven't tested it, but it should give you an idea of the expected workflow_):

```dart
final pb = PocketBase("http://127.0.0.1:8090");

final collection = await pb.collections.getOne("uktsrgciaq83ltm");

// add a new collection field...
collection.schema.add(SchemaField(
  id: "someRandomFieldId", // optional (it will be auto generated if missing)
  name: "myNewField",
  type: "text",
  required: true,
  // options differ depending on the field type
  // all field types and their options could be found in
  // https://pkg.go.dev/github.com/pocketbase/pocketbase@v0.12.1/models/schema
  // (the `json` value is the body key, for example the date options are https://pkg.go.dev/github.com/pocketbase/pocketbase@v0.12.1/models/schema#DateOptions)
  options: <String, dynamic>{
    "min": 10,
  },
));

// remove a field (aka. remove an element from the List)
collection.schema.removeAt(2);

// rename a field (aka. edit an existing List element)
collection.schema[1].unique = false;

// persist changes
await pb.collections.update(collection.id, body: collection.toJson());
```

---

> About auto migration. Can you please show us an example of how updating or adding of a column work there.
> How we can put migrating files in our repo and start a new project with the
same tables

The automigrations are automanaged, aka. when doing collection changes from the Admin UI or via the web API (as in the previous SDK example), it will automatically generate a js migration file for you in the `pb_migrations` folder. You can copy this folder to another location and place it next to your pb_data (_or if you want to specify a specific location, you can also use the `--migrationsDir="/path/to/pb_migrations"` flag when starting PocketBase; more info you can find with the `--help` flag_).

---


> When we ship a new version of our application adding columns or renaming
column shall be done automatically

I'm not sure what to recommend. As mentioned, for now offline/local-first data handling is not supported out of the box and this require some manual management from the developer side. I don't think there is a single generic solution for this since it really depends on your use case and the desired deployment flow, eg. how you are connecting to the remote server, how you are planning to propagate and sync changes, how you are planning to handle schema conflicts (eg. the user locally created a column with the same name but different id as your new remote update), etc.

**Comment by iampopal** [comment]
Thank you so much for your guidance

Great seeing that there is a way to add, remove or rename a column and
change its property

The automigration is a new way of migrating database and I think it will
solve our problem
As we want to automigrate our database with each new version of our flutter
app we ship.

About how we backup: we take user pb_data folder and save it in our server.

About sync: we need a sync feature but still don’t know how we can
implement it, this is a missing feature with package: drift we used so far.

Thank you for your response and great replay.

**Comment by iampopal** [comment]
I have just reviewed pb_migrations folder, it looks great and
understandable.

It will be much great and cool to have pb_migrations in dart language

Can you please tell us when we can have pb_migrations in dart language.

**Comment by ganigeorgiev** [comment]
Sorry, currently only Go and JS (via goja, an embedded go js runtime) migrations are supported and there are no plans for adding support for Dart since it will be too difficult and time consuming to maintain, document and test.

**Comment by iampopal** [comment]
And about sync: are there any plan to add offline first then sync to server feature?

**Comment by ganigeorgiev** [comment]
Offline/local-first data handling is in my todo to research it but for now is a very low priority and it is not planned for the near future.
