### ISSUE TITLE
Need to Start Pocketbase Server from Dart

### ISSUE THREAD

**Issue by iampopal** [pocketbase/dart-sdk#30]
We are about to develop an offline first then save backup of data.db at server application. 

we want to include pocketbase server in our app. 

How we can start/serve pocketbase server from dart code

**Comment by ganigeorgiev** [comment]
> we want to include pocketbase server in our app.

This will be difficult to achieve and can't be done with just the SDK.

In order to be able to run PocketBase on the user device:

- The app must be allowed to open a local HTTP port (eg. 8090 or other random one).

- Ship a special PocketBase executable with your app for the targeted device platform. For desktop this is easier, but for mobile there is no prebuilt android target at the moment and you'll have to build it on your own (https://github.com/pocketbase/pocketbase#running-and-building; you can also check https://github.com/pocketbase/pocketbase/issues/1768).

Then you could use [dart:io `Process.run`](https://api.dart.dev/stable/2.19.2/dart-io/Process/run.html) (or other more specialized library) to start the PocketBase executable that was shipped with you app, eg.:

```dart
final process = await Process.run('/path/to/pocketbase', ['serve', '--http="127.0.0.1:8090"', '--dir="/path/to/some/custom/pb_data"']);
```

_Note that you may have to implement some "watcher" service that will keep the process up in case the os decide to kill it._

**Comment by iampopal** [comment]
I think it will be great to have a package or the dart package by default include the runner and have a method to start/serve pocketbase

**Comment by iampopal** [comment]
And the executable of windows shall not be included in android and android not include in desktop so this way the each platform shall have their own executable and dart will run that executable

**Comment by iampopal** [comment]
We also want that migrations directory shall also be included in app, so when we add or change a table all users will effect meaning 
to all users the database modification shall go
