### ISSUE TITLE
I cant add pocketbase dependency in my flutter project. How to fix?

### ISSUE THREAD

**Issue by ZainRaza78** [pocketbase/dart-sdk#51]
Terminal:
[pocketbase] flutter pub add pocketbase
Because pocketbase depends on pocketbase, version solving failed.
exit code 65

**Comment by ganigeorgiev** [comment]
This doesn't really make sense. Maybe it is conflicting because your package name seems to be the same way as the imported one? Try to rename it.

In any case, I don't think there is an issue with the SDK because I'm not able to reproduce it locally and the pub.dev analysis most likely would have failed.

If you think that there is an issue with the SDK, please create a **minimal** reproducible repo and I'll have a look.
