### ISSUE TITLE
missed argument collection name inside buildUrl()

### ISSUE THREAD

**Issue by MayroTejada** [pocketbase/dart-sdk#55]
Hi first of all my overhaul experience with pocketbase its really great!!

Second I was workin with the function to get files from pocketbase with flutter and I realize something, in the documentation says that to get a file form a record you need to make another petition that return you a URI but I need to pass the next required arguments:

- RECORD MODEL
- FILENAME

the problem its with record model because in the file_service.dart of the sdk  the function "buildUrl" need 3 arguments 

- collectionId form the record model
- filename 
- recordId form the record model

but in the docs says:
Each uploaded file could be accessed by requesting its file url:
http://127.0.0.1:8090/api/files/COLLECTION_ID_OR_NAME/RECORD_ID/FILENAME

if I want to use the collection name it worn work because only expect the collection id argument or maybe I miss something reading the docs.

**Comment by ganigeorgiev** [comment]
It is not clear what actually is the issue you are trying to describe, nor where is failing.

In general you can use both the collection id or name to generate a file url.

**Comment by MayroTejada** [comment]
<img width="806" alt="Captura de pantalla 2024-04-11 a la(s) 12 20 35 p m" src="https://github.com/pocketbase/dart-sdk/assets/57577583/bc264fa2-6762-4d82-9a45-fbc7b6ad513c">

the problem its that collectionName its not used in the function to buildURl

**Comment by ganigeorgiev** [comment]
Ok, but why exactly this is a problem?

As mentioned earlier, the file url should work with either the collection id or name.

**Comment by MayroTejada** [comment]
the problem is that collection id is always required and doesn't give you the opportunity to use collection name instead.

**Comment by ganigeorgiev** [comment]
It seems that we are going in circles.

Sorry but I still don't understand why does it matter that we use the collection id.
Both urls (with the id and name) will point to the same file.

We use the collection id for backward compatibility reasons with earlier versions and because it cannot change which could break internal cache in case a collection is renamed.

If for whatever reason you want to use the collection name then you can simply create your own url helper. In the end `pb.files.getUrl` is just a convenient method to construct a url string and nothing more. It doesn't download or stream the resource and it is up to the developers to decide what they will do with the url.

I'll close the issue for now as I'm not planning adding extra knobs just to switch to the collection name, but if I'm misunderstanding something, please elaborate clearly on your use case to understand better the broader picture.
