### ISSUE TITLE
hi, will it support local database synchronization as well?

### ISSUE THREAD

**Issue by jinfagang** [pocketbase/dart-sdk#6]
let's users can view local data even with not celluar connection.

**Comment by ganigeorgiev** [comment]
For now there are no plans to implement offline data storage in the SDK and this is left to the developers to handle on their own.

Custom record IDs are supported (15 chars string) and you can create and store your records locally on the device without communing communicating with the web APIs. When cellular connection is available - push/sync with the remote.

**Comment by jinfagang** [comment]
@ganigeorgiev thanks. may i ask does realtime data using websocket? Is that possible using packetbase implement a very simple chat app?

**Comment by jinfagang** [comment]
@ganigeorgiev may i ask further how does it implemented? is that keeping a heart beat on both server and client? if so, will the heart beat cost too much battery life?

**Comment by ganigeorgiev** [comment]
When you call for example:

```dart
client.realtime.subscribe("example", (e) {
  print(e.action); // create, update, delete
  print(e.record); // the changed record
});
```

It will start a persistent/long-lived HTTP connection with the server. There is no "connection upgrade" like in WebSocket.

If the client doesn't receive any messages for more than 5 minutes, the server will drop the connection, and the dart client will try to reconnect automatically. The Dart SSE client code coud be found in https://github.com/pocketbase/dart-sdk/blob/master/lib/src/sse/sse_client.dart.

---

> if so, will the heart beat cost too much battery life?

I haven't done any benchmarks for the battery life usage, but it shouldn't be too much different than a WebSocket implementation for example.

**Comment by jinfagang** [comment]
@ganigeorgiev then what is the advantages for using http as long live connection? does there any further concern for this design pattern?

**Comment by ganigeorgiev** [comment]
The advantages over websockets is that it is a regular HTTP connection, there is no need of the hacky "http->websocket" protocol upgrade mechanism, no special SSL handling or firewall rules to manage, etc.

One "drawback" of SSE comprared to WebSockets is that with SSE you have only unidirectional connection, aka. server->client, thats why I mentioned that if you want to push/submit data back to the server (eg. as in sending a chat message), you have to make use the regular REST POST request (`client.records.create(...)`), when if you used WebSockets, you'll probably submit the chat message using the already opened connection because WebSockets are bidirectional.

**Comment by gedw99** [comment]
> let's users can view local data even with not celluar connection.

Marmot works with pocketbsse to do database synchronisation on the server.

so if one server goes down everything g keeps working . 

https://github.com/maxpert/marmot-pocketbase-flyio Works “ out of the box “

The pocketbase change events happen on the way through the middle tier. So they will continue to work I think but @ganigeorgiev would be able to answer that.

I am using this setup with golang and htmx and it’s working well across 5 data centers. 

The only thing you can’t do is a db schema update in real time - . Marmot does not support it yet. So you have to stop the server and restart it, and the normal pocket base migration will kick in.

I am planning to expose the marmot system inside pocketbsse gui so that all admins and devs can fully understand the replication going on. It will just show all servers and their sync state. 

Marmot can also do a snapshot and then you can add another server and it will pull the snapshot and then catchup .
