### ISSUE TITLE
Encountering a type casting error

### ISSUE THREAD

**Issue by PROTAG0N1ST** [pocketbase/dart-sdk#66]
## app_model.dart
![image](https://github.com/user-attachments/assets/880d0b7a-a4ff-435d-93a4-9ebbe6bfc46d)
## app_model.g.dart
![image](https://github.com/user-attachments/assets/072908da-5e32-4f24-a6a3-113ee3cbd241)

**Comment by ganigeorgiev** [comment]
This is expected and there no plans to change it unless there is a prominent use case that could convince me otherwise.

`RecordModel` no longer has a `id` field and instead it is replaced with getter and setter pair to avoid the object having the data in 2 different places (similar to the side-note mentioned in https://github.com/pocketbase/pocketbase/issues/5946#issuecomment-2496908756).

See https://pub.dev/documentation/pocketbase/latest/pocketbase/RecordModel/id.html.
